<a href="https://colab.research.google.com/github/pknemi/handling-categorical-data/blob/main/handling_categorical_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/customer.csv")

In [3]:
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [4]:
from sklearn.preprocessing import OrdinalEncoder

#ENCODING

In [5]:
review_order=["Poor","Average","Good"]
education_order=["School","UG","PG"]
encoder=OrdinalEncoder(categories=[review_order,education_order])

#TRANSFORMIN AFTER ENCODING

In [7]:
df[["review","education"]]=encoder.fit_transform(df[["review","education"]])

In [8]:
df

    age  gender  review  education purchased
0    30  Female     1.0        0.0        No
1    68  Female     0.0        1.0        No
2    70  Female     2.0        2.0        No
3    72  Female     2.0        2.0        No
4    16  Female     1.0        1.0        No
5    31  Female     1.0        0.0       Yes
6    18    Male     2.0        0.0        No
7    60  Female     0.0        0.0       Yes
8    65  Female     1.0        1.0        No
9    74    Male     2.0        1.0       Yes
10   98  Female     2.0        1.0       Yes
11   74    Male     2.0        1.0       Yes
12   51    Male     0.0        0.0        No
13   57  Female     1.0        0.0        No
14   15    Male     0.0        2.0       Yes
15   75    Male     0.0        1.0        No
16   59    Male     0.0        1.0       Yes
17   22  Female     0.0        1.0       Yes
18   19    Male     2.0        0.0        No
19   97    Male     0.0        2.0       Yes
20   57  Female     1.0        0.0       Yes
21   32    Male     1.0        2.0        No
22   18  Female     0.0        2.0       Yes
23   96  Female     2.0        0.0        No
24   16  Female     1.0        2.0       Yes
25   57  Female     2.0        0.0        No
26   53  Female     0.0        2.0        No
27   69  Female     0.0        2.0        No
28   48    Male     0.0        0.0        No
29   83  Female     1.0        1.0       Yes
30   73    Male     1.0        1.0        No
31   22  Female     0.0        0.0       Yes
32   92    Male     1.0        1.0       Yes
33   89  Female     2.0        2.0       Yes
34   86    Male     1.0        0.0        No
35   74    Male     0.0        0.0       Yes
36   34  Female     2.0        1.0       Yes
37   94    Male     1.0        2.0       Yes
38   45  Female     2.0        0.0        No
39   76    Male     0.0        2.0        No
40   39    Male     2.0        0.0        No
41   23    Male     2.0        2.0       Yes
42   30  Female     2.0        2.0       Yes
43   27    Male     0.0        2.0        No
44   77  Female     1.0        1.0        No
45   61    Male     0.0        2.0       Yes
46   64  Female     0.0        2.0        No
47   38  Female     2.0        2.0       Yes
48   39  Female     2.0        1.0       Yes
49   25  Female     2.0        1.0        No

In [9]:
from sklearn.preprocessing import LabelEncoder

#label encoding for target variable

In [12]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
encoder = LabelEncoder()

# Fit and transform the 'purchased' column of the DataFrame
df["purchased"] = encoder.fit_transform(df["purchased"])

In [13]:
df.head()

   age  gender  review  education  purchased
0   30  Female     1.0        0.0          0
1   68  Female     0.0        1.0          0
2   70  Female     2.0        2.0          0
3   72  Female     2.0        2.0          0
4   16  Female     1.0        1.0          0

In [14]:
df=pd.read_csv("/content/cars.csv")

In [15]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [21]:
df_new=pd.get_dummies(df[["fuel","owner"]]).astype('int')

In [59]:
new=df[['brand','km_driven','selling_price']]
concat=pd.concat([new,df_new],axis=1)

In [60]:
concat

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [41]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

#one hot encoding by splitting

In [48]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x=df.drop(columns=["selling_price"])
y=df["selling_price"]

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [49]:
x_train_new=one.fit_transform(x_train[["fuel","owner"]])
x_test_new=one.transform(x_test[["fuel","owner"]])

In [50]:
x_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [51]:
x_test_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [53]:
a=np.hstack((x_train[["brand","km_driven"]].values,x_train_new))

In [57]:
num_one_features=x_train_new.shape[1]
pd.DataFrame(a,columns=["brand","km_driven"]+one.get_feature_names_out().tolist()[:num_one_features])

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Hyundai,35000,1,0,0,0,0,0,0
1,Jeep,60000,1,0,0,0,0,0,0
2,Hyundai,25000,0,0,1,0,0,0,0
3,Mahindra,130000,1,0,0,0,1,0,0
4,Hyundai,155000,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
6497,Ford,35000,1,0,0,0,0,0,0
6498,Maruti,120000,0,0,1,0,0,0,0
6499,Tata,15000,0,0,1,0,0,0,0
6500,Maruti,32500,1,0,0,0,1,0,0
6501,Isuzu,121000,1,0,0,0,0,0,0